services:
  db:
    container_name: db
    hostname: datasource
    image: postgres
    volumes:
      - ./volume:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - 5432:5432
    restart: unless-stopped

  api:
    container_name: api
    hostname: localhost
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL_REMOTE}
    ports:
     - 4000:4000
    volumes:
      - ./bin:/usr/src/app/bin
      - ./application:/usr/src/app/application
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db

  www:
    container_name: www
    hostname: localhost
    build:
      context: ./test-haufe-client
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/
    ports:
      - 80:80
    restart: unless-stopped